---

- include: setup_server.yml tags=setup_server
- include: setup_mysql.yml tags=setup_mysql
- include: setup_app.yml tags=setup_app
- include: app_pip_req.yml tags=app_pip_req
- include: create_db_tables.yml tags=create_db_tables
- include: symlink_nginx.yml tags=symlink_nginx
- include: start_uwsgi.yml tags=start_uwsgi
- include: log_change.yml tag=report tags=log_change