---
 - name: apt-get update
   apt: update_cache=yes

 - name: install common packages needed for python application development
   apt: pkg={{item}} state=installed
   with_items:
     - libpq-dev
     - libmysqlclient-dev
     - libxml2-dev
     - libjpeg62
     - libjpeg62-dev
     - libfreetype6
     - libfreetype6-dev
     - zlib1g-dev
     - libxslt1-dev
     - mysql-client
     - mysql-server
     - python-dev
     - python-setuptools
     - python-imaging
     - python-mysqldb
     - python-psycopg2
     - build-essential
     - git
     - git-core
     - nginx
 - name: Generate ssh public key
   copy: src=id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=0644

 - name: Generate ssh private key
   copy: src=id_rsa dest=/root/.ssh/id_rsa mode=0600
