---
 #- name: creates uwsgi directory
 #  file: path=/etc/uwsgi/sites state=directory

 #- name: create uwsgi upstart script
 #  template: src=uwsgi.conf dest=/etc/init/uwsgi.conf

 - name: Copy conf_uwsgi to uwsgi sites
   copy: src={{webapps_dir}}/{{app_name}}/{{app_name}}/conf_uwsgi.ini dest=/etc/uwsgi/sites/{{app_name}}.ini
   # notify:
   #  - restart uwsgi