---
 - name: read-write git checkout from repo
   git:
    repo: "{{repo_url}}"
    dest: "{{webapps_dir}}/{{app_name}}"
    accept_hostkey: yes
    force: yes
    remote: "{{repo_remote}}"
    version: "{{repo_branch}}"
   register: gitrepo

 - name: Installing Requirements
   command: sh /root/c26-health-monitor/install_requirments.sh

 - name: Creating Virtualenv
   command: sh /root/c26-health-monitor/virtaul_env_cr.sh

 - name: Nginx config setup
   command: sh /root/c26-health-monitor/Flask_HealthMonitor/nginx_config_generator_other.sh