# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='icons',
            name='icons',
            field=models.FileField(upload_to='static/'),
        ),
    ]
