# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_column=b'model', max_length=255)),
                ('board_name', models.CharField(db_column=b'board_name', max_length=100, null=True)),
                ('ram_size', models.FloatField(db_column=b'ram_size', null=True)),
                ('is_dual_sim', models.BooleanField(db_column=b'is_dual_sim', default=False)),
                ('internal_space', models.FloatField(db_column=b'internal_space', null=True)),
                ('is_hd', models.BooleanField(db_column=b'is_hd', default=False)),
                ('phone_type', models.IntegerField(db_column=b'phone_type')),
                ('screen_width', models.PositiveSmallIntegerField(db_column=b'screen_width', null=True)),
                ('screen_height', models.PositiveSmallIntegerField(db_column=b'screen_height', null=True)),
                ('xdpi', models.FloatField(db_column=b'xdpi', null=True)),
                ('ydpi', models.FloatField(db_column=b'ydpi', null=True)),
                ('manufacturer', models.CharField(db_column=b'manufacturer', max_length=255)),
            ],
            options={
                'db_table': 'devices_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevicesRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_1', models.BigIntegerField(db_column=b'imei_1', default=0)),
                ('imei_2', models.BigIntegerField(db_column=b'imei_2', null=True)),
                ('android_id', models.CharField(db_column=b'android_id', max_length=50, null=True)),
                ('registered_on', models.BigIntegerField(db_column=b'registered_on')),
                ('gaid', models.CharField(db_column=b'gaid', max_length=255, null=True)),
                ('locale', models.CharField(db_column=b'locale', max_length=255, null=True)),
                ('sim_country', models.CharField(db_column=b'sim_country', max_length=255, null=True)),
                ('network_country', models.CharField(db_column=b'network_country', max_length=255, null=True)),
                ('gms_version', models.CharField(db_column=b'gms_version', max_length=255, null=True)),
                ('accounts', models.CharField(db_column=b'accounts', max_length=255, null=True)),
            ],
            options={
                'db_table': 'devices_registered',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column=b'created_on', null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column=b'updated_on', null=True)),
                ('is_visible', models.BooleanField(db_column=b'is_visible', default=False)),
            ],
            options={
                'db_table': 'device_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_version', models.CharField(db_column=b'android_version', max_length=255, null=True)),
                ('vendor_os_version', models.CharField(db_column=b'vendor_os_version', max_length=255, null=True)),
                ('vendor_name', models.CharField(db_column=b'vendor_name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'operating_system',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column=b'name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'timezone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_column=b'url', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'urls',
                'managed': False,
            },
        ),
    ]
