# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
