# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-07 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170207_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
