# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-08 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcodes',
            name='name',
        ),
    ]
