# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_groupcodes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='groups',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
