# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20170209_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcodes',
            name='master_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
