# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20170315_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='groupcodes',
            name='country_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.CountryCodes'),
        ),
    ]
