# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20170316_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcodes',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.CountryCodes'),
        ),
    ]
